---
kibana_version: 7.17.9

kibana_apt_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
kibana_repository: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"

kibana_elasticsearch_url: ["http://x.x.x.x:9200", "http://x.x.x.x:9200"]
kibana_elasticsearch_username: "elastic"

kibana_user: kibana
kibana_group: kibana

kibana_package: kibana
kibana_package_state: present

kibana_service_state: started
kibana_service_enabled: true

kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml

kibana_bin_path: /usr/share/kibana

kibana_server_port: 5601
kibana_server_host: "0.0.0.0"

http_proxy: "PROXY_IP"