---

es_heap_size: 8g

es_config:
 node.name: "{{ ansible_fqdn }}"
 cluster.name: "my-cluster"
 bootstrap.memory_lock: false
 xpack.security.enabled: true
 xpack.security.transport.ssl.enabled: true
 xpack.security.transport.ssl.verification_mode: certificate
 xpack.security.transport.ssl.keystore.path: /etc/elasticsearch/elastic-certificates.p12
 xpack.security.transport.ssl.truststore.path: /etc/elasticsearch/elastic-certificates.p12
 network.bind_host: 0.0.0.0
 discovery.zen.ping.unicast.hosts:
  - "node-01"
 cluster.initial_master_nodes:
  - "node-01"
 transport.host: "{{ ansible_fqdn }}"
 gateway.recover_after_time: 5m
 network.host: 0.0.0.0
 node.attr.box_type: warm
 node.attr.data: warm
